services:
  app:
    container_name: telegraf-app
    restart: unless-stopped
    working_dir: /usr/src/app
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    depends_on:
       db:
          condition: service_healthy

  db:
    image: mysql:8.0
    container_name: telegraf-db
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shop

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"

volumes:
  db-data: